export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'ADD_DISHES';
export const ADD_DISHES = 'ADD_DISHES';
export const UPDATE_FEEDBACK_FORM = 'UPDATE_FEEDBACK_FORM';
export const RESET_FEEDBACK_FORM = 'RESET_FEEDBACK_FORM';